title: Sentral Bisnis Digital
slogan: Semangat Transformasi Digital
description: >
  Sentral Bisnis Digital adalah perusahaan yang bergerak pada pembuatan dan pemeliharaan perangkat lunak, 
  pengadaan perangkat keras, instalasi jaringan, serta konsultan IT.
