name: Check my Astro site on pull request

on:
  # Trigger the workflow every time you created a pull request against the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  pull_request:
    branches: [main]

# Allow this job to clone the repo and create a deployment
permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Run checks
        uses: radenpioneer/astro-check@v0.1.2
        with:
          check-command: 'check' # Needs to be defined in your `package.json`.
          # path: . # The root location of your Astro project inside the repository. (optional)
          # node-version: 16 # The specific version of Node that should be used to build your site. Defaults to 16. (optional)
          # package-manager: yarn # The Node package manager that should be used to install dependencies and build your site. Automatically detected based on your lockfile. (optional)
          # resolve-dep-from-path: false # If the dependency file should be resolved from the root location of your Astro project. Defaults to `true`. (optional)
